### PR TITLE
enable configuration option ip_tenant_inheritance_order with inventory import

### PR DESCRIPTION
**Pull request by zvfvrv**
This PR aims to add the configuration option `ip_tenant_inheritance_order` with inventory import (check-redfish) as already available with vmware import.

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

thank you for the PR and this idea. Unfortunately I won't be able to just merge it as it will affect recent changes I made to the parsing of config files.

I would highly appreciate it if you could implement it again the `feature/improved-config-parsing` branch. This branch will be merge soon to `next-release` and this will become the default.

If you don't care who is doing the integration then I could also add it to the code.

Just let me know what you would prefer.

Thank you

**Comment by zvfvrv** [comment]
Hi @bb-Ricardo ,
Ok no problem I will take care of it, I will implement the changes against the other branch.

Thanks

**Comment by bb-Ricardo** [comment]
awesome, thank you so much.

**Comment by bb-Ricardo** [comment]
Hey @zvfvrv,

I just merged the configuration rewrite to `development` You could just use this branch.

Thank you

**Comment by zvfvrv** [comment]
I am closing this PR since it is replaced by #281

**Pull request closed without merging**
