### PR TITLE
Log on stdout by default (instead of stderr)

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

good idea, I assumed it logs to stdout by default and never checked.

But you just need to add `sys.stdout` to StreamHandler in line `106`.

**Comment by n-rodriguez** [comment]
> But you just need to add `sys.stdout` to StreamHandler in line `106`.

I'm gonna try it right now :)

**Comment by n-rodriguez** [comment]
> But you just need to add `sys.stdout` to StreamHandler in line `106`.

Fixed! Thank you!

**Comment by bb-Ricardo** [comment]
Great work, thank you. Will add it to the next release. Still have some tasks open for this project but 5 other projects with fix/improve as well.

Not sure when but soon it will be there 😅

**Pull request merged**
