### PR TITLE
Fix filename on module -> sources -> common

### PR DESCRIPTION
**Pull request by quentinlegay**

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Goog point, thank you very much. I assume the imports need to be adopted as well. Could you have a look please? I'm currently without access to a computer.

Thank you.

**Comment by quentinlegay** [comment]
Yes, you're right and I forgot. I've just made the change.

Thanks

**Comment by bb-Ricardo** [comment]
Awesome, thank you. Will take care of this next week.

**Comment by bb-Ricardo** [comment]
thank you very much. Sorry it took so long to merge.

**Pull request merged**
