### PR TITLE
Add OpenStack & oVirt Support

### PR DESCRIPTION
**Pull request by dupondje**
We  use the netbox-sync tool here, but also wanted to import data from Openstack into Netbox.
As this was not available yet, we did build it :)

This pull req adds support for openstack source and syncs clusters (availability groups) / hypervisors and vm's.

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

This is amazing, thank you.

First of all: I don't have experience in OpenStack and also no OpenStack environment to test.

In order to add and maintain this I need your help. Would you commit to support and maintain the source?

Would you do that?

**Comment by dupondje** [comment]
Hi,

As long as we have an OpenStack environment I can help with it :)
If things break on some other openstack version or so, then its a bit harder to debug ...

But as we needed openstack sync, and we used your project as a base, it was the right thing to contribute the source plugin!

**Comment by bb-Ricardo** [comment]
Great, this sounds promising.

Do you think this is useful to test your import against?: https://github.com/rackerlabs/mimic

What we still need:
* is a updated `settings-example.ini`
* a description in docs/
* a code clean up 😄 

I See you copied the VMWare handler. But it seems there quite some config vars which are not used. I know it is quite a bit of work but it would help users and future developers to understand what's possible and how it works.

Then I would happily merge your PR and slowly prepare the next release 🤩 

Thank you.

**Comment by bb-Ricardo** [comment]
Hi @dupondje, I would really like to see this source in the next release. Did you have some time to polish this PR a bit?

**Comment by dupondje** [comment]
@bb-Ricardo : its on my TODO list :) i'll push it when done

**Comment by bb-Ricardo** [comment]
> @bb-Ricardo : its on my TODO list :) i'll push it when done

Awsome

**Comment by bb-Ricardo** [comment]
Hi @dupondje, was wondering if this is ready to merge or if you're still working on this.

**Comment by bb-Ricardo** [comment]
Hey @dupondje, can you please let me know about the current status of this PR?

**Comment by ludvik78** [comment]
@dupondje do you have working code for nebox 3.3.0?

**Comment by dupondje** [comment]
As netbox-sync received a lot of changed, I modified the sync code for OpenStack also to the latest netbox-sync version.
Testing everything out atm, but seems to work fine :)

**Comment by ekrichbaum** [comment]
Is this functional at this stage?  Can we get it pushed to main?

**Comment by ekrichbaum** [comment]
I rebranched and imported it.  Had to fix a few typos and the dependencies but doesn't quite work for me with Ovirt.  Let me get these hammered down and I'll resubmit a pull.

**Comment by bb-Ricardo** [comment]
Hi,

The issue with this PR is a maintainer which takes care of this type of source. I don't have an environment to test the integration and therefore would need someone who would take on this role.

**Comment by bb-Ricardo** [comment]
> Gladly. I rebased from your master, integrated his code, fixed some typos and imports and an additional error trap (Ovirt returning a NoneType for provisioned_size).
> 
> Ovirt is now working and a few more runs to be sure I got it, then I'll start the OpenStacks roll. Once I have it all together, I'll start a new PR. (btw, I had to unpin pyyaml and pyvmomi versions).

Bumped versions in development branch. Would this work for you?

**Comment by ekrichbaum** [comment]
Sure.  I see you updated the requirements across the board. I had just unpinned.  oVirt is working well. Openstacks is proving more difficult although I do have some of the data happening.  A server object in Openstack doesn't actually have things like ram and vcpu in the object, so that piece is still pending. I do have it collecting data in a fashion though. that piece just needs work.  I can push the PR in general as new or make adjustments in that branch directly.  Your call.

**Comment by ekrichbaum** [comment]
Fixed working oVirt and 50% openstacks PR: #389 

This one should be closed in favor of the more up to date.

**Pull request closed without merging**
